- name: variables
  hosts: localhost
  vars:
    Course: "ansible"
    Trainer: "srikar"
    Duration: "120hrs"
  tasks:
  - name: print information
    ansible.builtin.debug:
     msg:  msg: "Hi, We are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}."
