- name: variable
  hosts: localhost
  vars:
    Course: "ansible"
    Trainer: "Srikar"
    Duration: "120hrs"
  tasks:
  - name: we are overriding the variables
    vars:
      Course: "Devops"
    ansible.builtin.debug:
      msg: "Hi, We are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}."
  
  - name: print information
    vars:
      Course: "Devops"
    ansible.builtin.debug:
      msg: "Hi, We are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}."
      
    
      
    

      


