- name: variables from prompt
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: enter the user name
    private: false

  - name: PASSWORD
    prompt: enter the password 
    private: true
     
  tasks:
  - name : print the information
    ansible.builtin.debug:
    msg: "Hi, username: {{USERNAME}}. password: {{PASSWORD}}"