- name: variables from prompt
  hosts: localhosts
  vars_prompt:
  - name: USER_NAME
    prompt: enter the user name
    private: false 

  - name: PASSWORD
    prompt: enter the password 
    private: true  
  tasks:
  - name: to enter the user id and password 
    ansible.builtin.debug:
      msg: "Hi, UserName: {{USER_NAME}}. password: {{PASSWORD}} have entered"