- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{course | default('Ansible') }}"


- name: upper case
  hosts: localhost
  vars: 
   greets: "enter the values"
  tasks:
  - name: enter the lower
    ansible.builtin.debug:
     msg: "pls {{greets}} | upper"
  